name: Deploy to Production
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: superfly/flyctl-actions/setup-flyctl@v1.4
      - run: flyctl deploy --config fly-production.toml --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
