name: Deploy to Staging
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: superfly/flyctl-actions/setup-flyctl@v1.4
      - run: flyctl deploy --config fly-staging.toml --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
